manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: Fushilaofang
      url-base: https://github.com/Fushilaofang
  projects:
    - name: zmk
      remote: petejohanson
      revision: feat/pointers-move-scroll
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: Fushilaofang
      revision: main
    - name: zmk-split-peripheral-input-relay
      remote: Fushilaofang
      revision: main  
  self:
    path: config
